version: '3.9'

services:
  db:
    image: postgres:15

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc12345
      POSTGRES_DB: pos-api-web-development-37

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    container_name: pos-api

    restart: always

    ports:
      - '5000:5000'

    env_file:
      - .env

    depends_on:
      - db

volumes:
  postgres_data:
